#!/bin/bash

WORLD_LEADERS=(MODI TRUMP PUTIN XIJINPING)
echo ${WORLD_LEADERS[@]}

WORLD_LEADERS=(MODI TRUMP PUTIN XI JINPING)
echo ${WORLD_LEADERS[@]}

WORLD_LEADERS=("MODI" "TRUMP" "PUTIN" "XI JINPING")
echo ${WORLD_LEADERS[@]}